import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "./Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Connectra Technologies",
  description: "Generated by create next app",
  icons: {
    icon: "/logofinal.png",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
    <link rel="icon" href="/logofinal.png" type="image/png" />
  </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >   
      <Navbar />
        <main className="pt-20">
          {children}
           <Toaster position="top-center" reverseOrder={false} />
        </main>
        <Footer/>
      </body>
    </html>
  );
}
